### ISSUE TITLE
Expanding elements without using `Box`

### ISSUE THREAD

**Issue by kbilsted** [TomaszRewak/C-sharp-console-multiplexer#14]
Just learning the framework. Is this as expected? I thought it required a ´Box´ in order for the content to be centered.

    class Program
    {
        static void Main(string[] args)
        {
            ConsoleManager.Setup();
            ConsoleManager.Resize(new Size(150, 40));

            ConsoleManager.Content =

                    new Border()
                    {
                        Content =
                            new HorizontalStackPanel()
                            {
                                Children = new[] { new TextBlock { Text = "Hello world" }, new TextBlock { Text = "22Hello world22" }, }
                            }
                    }
                ;

            Console.ReadKey();
        }

![image](https://user-images.githubusercontent.com/1616338/70261373-945cdf80-1792-11ea-867f-3d9bd67ecada.png)

**Comment by TomaszRewak** [comment]
Do you want to center to border or the text within it?

**Comment by kbilsted** [comment]
I'm just reading the docs and trying it out. eg

    Box
    Aligns the Content control vertically (Top/Center/Bottom/Stretch) and horizontally (Left/Center/Right/Stretch).

    HorizontalStackPanel
    Stacks multiple controls horizontally.

since I'm not using `Box` i dont understand why the content is maxmized. Perhaps details are missing in the docs?

**Comment by TomaszRewak** [comment]
The `Border` will always take all of the available space when not stored in a control that defines a different layout behavior.
The only way to center elements is using the `Box` control.
The proper way of implementing it is described in #13
