### ISSUE TITLE
feature: listview

### ISSUE THREAD

**Issue by kbilsted** [TomaszRewak/C-sharp-console-multiplexer#16]
What are your thoughts on listviews? Is it something I have to compose from existing components?

for my application I need to display a lot of lines and have the user select one of them. The line currently being the candidate for selection is hightligted and some hotkey defines that the selection is made (possibly enter).

Naviagation of the current selected line needs to be accessed from outside the component (eg. a method MoveUpOne(), MoveUpPage(), MoveDownOne(),..). This allows me to combine the listview with a textfield so that the content of the listview is filtered.

**Comment by kbilsted** [comment]
Perhaps the nicest solution would be to extend the datagrid such that it has a notion of a current selected line which is highlighted and some input handling for when cursor keys or enter is pressed.

**Comment by TomaszRewak** [comment]
I'm sorry, but I think that this control is too specific and indeed should be composed from existing components.
It should be easily achievable by using a `StackPanel` with `TextBlock`s wrapped in `Background`s.
And everything controlled by a custom `IInputListener`.
To get a little bit cleaner code you could create a `ListView` and `ListViewItem` by inheriting the `SimpleControl` and exposing just the desired interface.

My rule of thumb when deciding if something is too complex to be included in the core library is: if it's not available in the HTML/CSS, but people still manage to relatively easily create it with lower level components, then it (probably) should not be available here neither.

**Comment by kbilsted** [comment]
HTML does have a list view :-) for applications such controls are very common. But maybe your framework is n9t targeting that.

**Comment by TomaszRewak** [comment]
Well, the list view in the HTML (if you are talking about the `<ul>` tag) is no much different then the `VerticalStackPanel`. Anything more then that has to be achieved either by custom styling and/or more advanced layouts.

There is nothing it the pure HTML that provides an out-of-the-box list with highlights/selection/filtering in a single control. Fo some of that you will actually need some additional code-behind in a form of js.

Of course, in the HTML/CSS roam you can use an external library to get a nice list view. And I highly encourage creating control sets associated with this project as well. It's simply that this project was meant to be a layout management library for console applications and (at lease as long as I'm the only contributor which brings some time constrains) I want to keep it this way.

**Comment by kbilsted** [comment]
No not the `UL` tag. I'm referring to the `<select>` tag https://www.html.am/html-codes/forms/html-select-lists.cfm 

Regarding the filtering, above I wrote I would want to extend the listview myself ;)

**Comment by TomaszRewak** [comment]
Oh, then you not talking about simple lists, but drop-down lists/menus once again.

In that case I'm merging this topic with #12 and for now marking it as `wontfix`.

And for anyone stumbling upon this thread in the future:
If you want to create a simple list view with multiple options:
> It should be easily achievable by using a `VerticalStackPanel` with `TextBlock`s wrapped in Backgrounds.
And everything controlled by a custom `IInputListener`.
To get a little bit cleaner code you could create a `ListView` and `ListViewItem` by inheriting the `SimpleControl` and exposing just the desired interface.

**Comment by kbilsted** [comment]
This of course ia your choice, i still think if the listview is operative using the keyboard scrolling content when the list is larger than the allocated screen, needs be addressed and hence a simple decorator wont suffice

**Comment by TomaszRewak** [comment]
But if you predict that the list might be longer than the available space, then you should host the vertical stack panel containing it in a `VerticalScrollPanel`. `VerticalScrollPanel` supports keyboard navigation. But if you want to override the default behavior with something a little bit more complex, so that the list would follow the selected item, it's also very easy.

Implementing this logic is as simple as that:
```
class MyScrollableListController : IInputListener
{
	...

	public void OnInput(InputEvent inputEvent)
	{
		switch(inputEvent.Key.Key)
		{
			case ConsoleKey.UpArrow:
				_selectedItem--;
				break;
			case ConsoleKey.DownArrow:
				_selectedItem++;
				break;
			default:
				return;
		}

		_selectedItem = Math.Max(Math.Min(_selectedItem, myListView.Length), 0);

		myListView.Highlight(_selectedItem);
		scrollPanel.Top = _selectedItem - scrollPanel.Size.Height / 2;
	}
}
```

I don't see a point in involving the framework in this process.
