### ISSUE TITLE
Create an editor

### ISSUE THREAD

**Issue by kbilsted** [TomaszRewak/C-sharp-console-multiplexer#17]
I kind of need some guidance. I am trying to implement a simple editor. Im using the new `BreakPanel`. My issue is that the content is larger than the allocated screen. So when I move right I expect the content to change when I reach the end of the lowest line. It doesn't

I also would expect the `TextBox` to support arrow up/down.

Maybe I need to 

		class Program
		{
			static void Main(string[] args)
			{
				// optional: adjusts the buffer size and sets the output encoding to the UTF8
				ConsoleManager.Setup();

				// optional: resizes the console window (the size is set in a number of characters, not pixels)
				ConsoleManager.Resize(new Size(50, 10));

				var textBox = new TextBox()
				{
					
					Text = @"1 alsjdasldk
	2 asjdkalsj
	3 iieieiei
	4 fkkrkrk
	5 fldksjf
	6 fsdlkfjls
	7 dslakfj
	8 sldkf
	9 sdlkf
	10 dkdkdkdk
	11 jdjdjdjd
	12 qpqpqpqpq

	the end", 
				};

				ConsoleManager.Content =
					new Border()
					{
						Content = new BreakPanel(){Content =  textBox, }
					};

				var input = new IInputListener[] {textBox};

				while (true)
				{
					Thread.Sleep(10);
					ConsoleManager.ReadInput(input);
				}

				Console.ReadKey();
			}
		}

wrapping it in a ScrollPanel gives a nice schrollbar. But no scrolling 

            ConsoleManager.Content =
                new Border()
                {
                    Content =
                        new VerticalScrollPanel()
                        {
                            Content = new BreakPanel() {Content = textBox,}
                        }
                };

**Comment by TomaszRewak** [comment]
Ah, right, I indeed forgot to add support for up/down arrows. I will fix that in the evening.

When it comes to the scrolling along with the selection, that's a little bit more tricky. I will have to think what the right solution for that might be.

Probably the simplest way to implement that would be to compare the `CaretStart` and `CaretEnd` positions of the text box with ~~the value of `Cell.MouseListener.RelativePosition.X` produced by the scrollbar in its top-left and bottom-left corners~~ the manually calculated offset of the text based on the width of the container. Based on that one could decide if the selection (or if `CaretStart == CaretEnd` the cursor), is with the view. And if not, updating the `Top` property of the `VerticalScrollView` would be the way to adjust it.

**Comment by TomaszRewak** [comment]
I will revisit that in 2-3 hours.

**Comment by kbilsted** [comment]
Sure, just don't get stressed out :-)

**Comment by jzabroski** [comment]
As pianist Glenn Gould once said, the ideal ratio of audience to performers is 1:1

**Comment by TomaszRewak** [comment]
OK, the vertical navigation is there. 

When it comes the scrolling with the caret, you should implement it in the way I've mentioned above.
If you detect that that the `CaretStart` or the `Text` property of the `TextBox` has changed, calculate the offset manually and scroll the `VerticalScrollPanel` to that position. Yo simply have to count the number of `\n` characters and lines longer then the container width before the `CaretStart`. I believe you can do that :D
When it comes to the `Text` changes, you can simply compare references so that you don't have to compare entire strings on each iteration.

**Comment by kbilsted** [comment]
@TomaszRewak  wow nice you are really fast ;-)

I'm not sure why you don't want to implement basic navigation as part of the library? Like you hint, the calculations are semi-complicated (especially if you support copy/paste) and there is no documentation on it except as issues.

If you have to implement too much yourself you may easily scare new application developers away (if those are your target group?)

**Comment by TomaszRewak** [comment]
That's true, having to add to much code on top of the library is rarely a good thing.
But in this case I simply don't consider the the autonavigation in the scrollable multiline text boxes as a "basic" feature. Especially that it can be viewed in multiple different ways based on unique project requirements.

Indeed, this framework is also aimed at new app devs. But it's not meant to replace standard gui frameworks when creating more complex applications. In my opinion console apps and desktop apps have different roles to play. And should be designed differently. Take a look at the `htop` vs the task manager. Devs of the `htop` might have added drop-down menus when selecting a row. But they decided to make a design that is console driven. And the ConsoleGUI is a perfect fit for projects that want to create rich, console driven applications. But not necessarily for 1:1 porting of desktop apps.
From that perspective I consider creating a fully fledged text editor as an advanced use of the library (though still possible and encouraged) and in this case I would expect the developer to take care of those smaller implementation details.

**Comment by kbilsted** [comment]
I think you are right. Sorry my comment was actually targeted the combobox / listview. 

Its a really neat library and you are really fast at implementing new features. If you want to develop an app i still think you are in for a bot of a rough time. Most apps are about data entry and data presentation and access to functionality  (think menus). And your front page example is a chess game.  Im not sure how used your library is, but i think it may scare some away that thr current focus seems to be on being a layout engine and let authors deal with making the common gui components.

A simple functioning editor is possibly a bit over the top. Although it makes for easy administration of user settings, enable more complex data entry etc.

**Comment by TomaszRewak** [comment]
FYI, caret following now works with single line text editors.
The status of the caret following in multi line text editors is still `wontfix`.
