### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by lol768** [TomaszRewak/C-sharp-console-multiplexer#2]
Please make it clear in the README that this targets netstandard2.0 (a good thing!) and not .NET framework :)

**Comment by TomaszRewak** [comment]
Thanks for pointing it out.
I will add this comment as soon as the #3 is fixed (just to be sure that it actually works on other platforms).

**Comment by TomaszRewak** [comment]
Done in a88c428efc070f5934baee33198fc8d21c7b9c21 ;)

**Comment by lol768** [comment]
Thanks!

**Comment by TomaszRewak** [comment]
Thank you!
