### ISSUE TITLE
Create Controls of XML-files

### ISSUE THREAD

**Issue by doEggi** [TomaszRewak/C-sharp-console-multiplexer#28]
It might be possible to use **XML-files** to create a _"Control-Tree"_, it would be a bit easier to use and is just an idea...

**Comment by TomaszRewak** [comment]
Hmm, yeah, that would be possible. Though I don't think it would be trivial to bring it to a usable state.

The main challenges I can see are:

1) Interacting with the elements from the generated code. The simple solution of just generating the structure and returning its root would not be sufficient, as it would not be possible for developers to obtain references to the deeply nested controls. We would have to introduce some id-based element identification mechanism what would also generate top level references to those components.

2) Splitting layout into multiple files. Currently it's as simple as splitting the layout generation logic into multiple functions that live in different files. With xmls we would have to introduce a custom file import mechanism - which would complicate the problem of retrieving nested UI controls even more complicated.

3) Providing live access to UI elements when editing the xml structure without recompiling. Usually that's what developers expect - they don't want to be forced to rebuild the entire project every time they make a change to an xml file to be able to access newly added elements. And both with a pre-build step of the .csproj and code generators that would not be possible. We would have to investigate how does the VS do it for WPF projects and their XAML files.

4) Conditional layout generation. Would we want to embed logic into the xml files? We might end up with something as complex as WPF data bindings and layout templates.

So overall it indeed seems like a cool idea (thanks for the suggestion!), but I'm not sure if it's worth pursuing.

**Comment by doEggi** [comment]
Ever again :)
If not, it isnt a Problem, because its already very simple and nice in my opinion to use...
