### ISSUE TITLE
Missing using directive in TabPanel example

### ISSUE THREAD

**Issue by tommiecc** [TomaszRewak/C-sharp-console-multiplexer#34]
There is a missing using directive in the TabPanel example. When I was trying to implement the example this error was thrown:
`error CS0246: The type or namespace name 'IControl' could not be found (are you missing a using directive or an assembly reference?)`

The fix was to add `using ConsoleGUI;` to the TabPanel.cs file. I suggest that the example is updated unless it is an error that is solely on my machine for some reason.

**Comment by TomaszRewak** [comment]
Nicely spotted and thanks for reporting!
I've added the missing directive to the example.
Thanks!
