### ISSUE TITLE
This sort of framework is called a "TUI" (text user interface) framework

### ISSUE THREAD

**Issue by ddevault** [TomaszRewak/C-sharp-console-multiplexer#4]
FYI. GUI is graphical user interface.

**Comment by TomaszRewak** [comment]
Yeah, I know, I was thinking for some time on how to name/advertise this project.
And even though the current name is not 100% accurate I figured that people searching for such projects will more likely look for a "console based gui framework" then a "tui framework".
But I totally agree with you.

**Comment by ddevault** [comment]
>And even though the current name is not 100% accurate I figured that people searching for such projects will more likely look for a "console based gui framework" then a "tui framework".

Eh, I highly doubt that. No other TUI frameworks are advertising themselves as GUI frameworks.

**Comment by TomaszRewak** [comment]
I actually disagree.
When it comes to the TUI .NET frameworks, 2 out ot 3 biggest alternatives to this project (Gui.cs, SadConsole and Console Framework) mention GUI in their readmes (and the biggest one is actually called Gui.cs). Only the Console Framework (the smallest out of those thee) refers to itself as a TUI framework.

**Comment by ddevault** [comment]
Marketing potential over accuracy. Windows people, man.
