### ISSUE TITLE
Typo in DockedControlPlacement enum

### ISSUE THREAD

**Issue by araney** [TomaszRewak/C-sharp-console-multiplexer#5]
Should be `DockedControlPlacement` but is `DockedContorlPlacement`

https://github.com/TomaszRewak/C-sharp-console-gui-framework/blob/01a08fffb825b6eadd6e5be1e5315b837ccb6027/ConsoleGUI/Controls/DockPanel.cs#L13

**Comment by TomaszRewak** [comment]
Thanks!
Fixed.
