### ISSUE TITLE
Support Console Resize w/ Caveat Lector

### ISSUE THREAD

**Issue by jzabroski** [TomaszRewak/C-sharp-console-multiplexer#7]
@bpiepiora wrote:
> Is it possible to detect size changes of the console and update the content accordingly?

@jzabroski wrote:
> Handling console window size changes is not safe: https://stackoverflow.com/a/34208406

@TomaszRewak wrote
> Yeah, unfortunately that's the case.
But actually thinking about it I could add a new method to the ConsoleManager that the user would have to call each "frame" (the same way it's currently implemented for keyboard input handling) that would simply check if the size of the window has changed as compared to the value from the previous frame.
> It wouldn't be 100% foolproof (because if the window size would change to a different value and back to the initial value during one frame it might break the layout), but it would still be better than nothing.

**Comment by TomaszRewak** [comment]
Done in 46e20627c583539f8eb1b03cc0242b079d9f7492 ;)
